# IAP API Automation Configuration
base.url=http://subscription-admin-backend-service-jwr-qa-8.jwrnonprod.int
tab.base.path=/subs-admin/api/v1/tab
tabs.fetch.path=/subs-admin/api/v1/tabs
pass.base.path=/subs-admin/api/v1/pass

# Auth Token - Update before running tests
auth.token=eyJraWQiOiI1YTA0YWYzMi1iMmVkLTRlMDktYTc4ZC02Y2RmYzhiOGRiODYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2NiIsInVzZXJuYW1lIjoic3VyYmhpIiwicGVybWlzc2lvbiI6WyJlZGl0IiwidmlldyJdLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDAxMDYxNDAsImV4cCI6MTc0MDEwNzM0MH0.Mjj-N8vHKOfJznjvOq5GPsTiquZ2pKf8ZrzbOaOkyreTz5qEdhlyRlUzSrMlmRYZWMdD4AVjtVN0HQuejmaOji00B7S3o3KTlFaffDqOe4SwlwsnmNprqx_YvE_PJWCLQaCStEB5qO3AHK5UChinfdrgbtO30hHURkL28OC-BPR3zk4Ya_-9YcXWa6P2kNsoHKCgNNdK1WUyMEgNnKUP3RwwFDxll_5r6nnO-hYterAyXwSluS2RV7SO-zPa4aA6xRrmE3vB19iR2B0YZekslsqo_crf1fWfGYMp0mdy7gPDICC-Rp525jyO39awPc8NWpm2l0KvU27DmA4jnsznRg

# Product Configuration
product.id=RUMMY
tab.type.gems=gems
tab.type.coins=coins
tab.type.tournament=tournament